# Generated by Django 4.2.11 on 2024-04-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='Title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
